version: "2"
services:
    mysql:
      image: mysql:5.6
      restart: always
      container_name: keys-db
      volumes:
        - ./mysql:/var/lib/mysql
        - ./mysql-logs:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - TZ='Europe/Paris'
    mailer:
      image: mwader/postfix-relay:latest
      container_name: keys-mailer
      environment:
        - POSTFIX_myhostname=small-keyring.com
    webserver:
      image: nginx:alpine
      restart: always
      container_name: keys-www
      working_dir: /server
      volumes:
        - ./server:/server
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx-logs:/var/log/nginx
        - /var/lib/ssl:/var/lib/ssl
      ports:
        - "80:80"
        - "443:443"
    php-fpm:
      build: php-fpm
      restart: always
      container_name: keys-php
      working_dir: /server
      volumes:
        - ./server:/server
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./home:/home/keys


